// Generated by install/release.sh — do not edit by hand.
// Mirrors smartbar/__init__.py so the popover, the CLI, the app bundle's
// Info.plist and the git tag all name the same build.
enum AppVersion {
    static let current = "0.8.1"
}
