#!/usr/bin/env bash
# Build + install the NATIVE SwiftUI menu-bar app (recommended macOS UI),
# or --uninstall. Requires macOS 13+, Xcode Command Line Tools, claude-swap.
# Takes over the com.ductran.ai-smartbar LaunchAgent label from the Python
# variant, so only one AI_smartbar starts at login.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG="$REPO/macos-swift"
APP_DIR="$HOME/Applications/AI_smartbar.app"
PLIST="$HOME/Library/LaunchAgents/com.ductran.ai-smartbar.plist"

# Canonical version lives in smartbar/__init__.py; install/release.sh bumps it
# there and everything else (this bundle, Version.swift, the git tag) follows.
VERSION="$(sed -n 's/^__version__ *= *"\(.*\)"/\1/p' "$REPO/smartbar/__init__.py")"
VERSION="${VERSION:-0.0.0}"

# The commit this bundle is being built FROM. The version above only moves on
# a release, so on a channel=main device it cannot say which code is inside —
# see macos-swift/Sources/AISmartbar/BuildInfo.swift. Empty is a supported
# answer (no git, or a checkout exported without one); the app then names the
# version alone.
BUILD_SHA="$(git -C "$REPO" rev-parse HEAD 2>/dev/null || true)"

AUTO_UPDATE=1
CHANNEL_ARG=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --uninstall)
      launchctl unload "$PLIST" 2>/dev/null || true
      rm -f "$PLIST"
      rm -rf "$APP_DIR"
      "$REPO/install/macos-update.sh" --uninstall >/dev/null 2>&1 || true
      echo "AI_smartbar.app uninstalled."
      exit 0 ;;
    --no-auto-update) AUTO_UPDATE=0; shift ;;
    --channel)   CHANNEL_ARG=(--channel "${2:?--channel needs release|main}"); shift 2 ;;
    --channel=*) CHANNEL_ARG=(--channel "${1#*=}"); shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# This device's own settings. launchd gives a GUI app no shell environment at
# all, and the plist below is rewritten from scratch on every update, so
# ~/.config/ai-smartbar/config.env is the only durable place for them — folded
# in here, and therefore re-applied by every update, since applying an update
# IS re-running this script. Never fatal: a device with an unreadable config
# still gets a working agent.
CONFIG_PLIST="$("$REPO/bin/ai-smartbar" --print-config plist || true)"

command -v swift >/dev/null \
  || { echo "Swift toolchain missing — run: xcode-select --install"; exit 1; }
command -v cswap >/dev/null || [[ -x "$HOME/.local/bin/cswap" ]] \
  || { echo "Install claude-swap first (pipx install claude-swap; then cswap add)"; exit 1; }

echo "Building AI_smartbar (release)…"
swift build -c release --package-path "$PKG"
BIN="$(swift build -c release --package-path "$PKG" --show-bin-path)/AISmartbar"
[[ -x "$BIN" ]] || { echo "Build produced no binary at $BIN"; exit 1; }

echo "Bundling ${APP_DIR}…"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$BIN" "$APP_DIR/Contents/MacOS/AISmartbar"

# The app icon, built from the one committed asset that every platform shares
# (generated by smartbar/paint/app_icon.py). A full .iconset rather than a
# one-shot `sips --format icns`: Login Items, the Finder list view and the
# notification badge all render at 16-32pt, and a lone 1024 representation
# downscaled that far goes soft exactly where the icon is seen most.
#
# Never fatal. An install that cannot draw an icon is a working install with
# a generic icon; failing here would trade the whole app for cosmetics — and
# this runs unattended from the updater, where that trade is worse still.
ICON_SRC="$REPO/assets/ai-smartbar.png"
ICONSET="$APP_DIR/Contents/Resources/AppIcon.iconset"
if [[ -f "$ICON_SRC" ]] && command -v sips >/dev/null \
   && command -v iconutil >/dev/null; then
  rm -rf "$ICONSET"
  mkdir -p "$ICONSET"
  # nominal:pixels — pixels != nominal is the @2x (Retina) variant.
  for spec in 16:16 16:32 32:32 32:64 128:128 128:256 256:256 256:512 \
              512:512 512:1024; do
    nominal="${spec%%:*}"
    pixels="${spec##*:}"
    suffix=""
    [[ "$pixels" == "$nominal" ]] || suffix="@2x"
    sips -z "$pixels" "$pixels" "$ICON_SRC" \
         --out "$ICONSET/icon_${nominal}x${nominal}${suffix}.png" \
         >/dev/null 2>&1 || true
  done
  iconutil -c icns "$ICONSET" -o "$APP_DIR/Contents/Resources/AppIcon.icns" \
    || echo "WARNING: could not build the app icon — using the generic one." >&2
  rm -rf "$ICONSET"
else
  echo "WARNING: $ICON_SRC missing — the app will use the generic icon." >&2
fi
cat > "$APP_DIR/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>com.ductran.ai-smartbar</string>
  <key>CFBundleName</key><string>AI smartbar</string>
  <!-- Without this, macOS names the login item by CFBundleExecutable, so
       Login Items & Extensions and its "can run in the background" alert
       both call this app "AISmartbar". -->
  <key>CFBundleDisplayName</key><string>AI smartbar</string>
  <key>CFBundleExecutable</key><string>AISmartbar</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>SMARTBARBuildSHA</key><string>${BUILD_SHA}</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
EOF

# The Swift linker ad-hoc signs the bare executable. Once it is wrapped in
# an app bundle with Info.plist, sign the bundle so `codesign --verify` and
# Finder launches see a consistent local application.
codesign --force --deep --sign - "$APP_DIR"

# LaunchServices caches a bundle's Info.plist keyed on the .app DIRECTORY's
# own mtime, and every write above lands INSIDE Contents/ — which leaves that
# mtime exactly where the FIRST install left it. So on a device that already
# had the app, macOS goes on serving whatever it recorded back then: the icon
# added in 1.0.2 never appeared in the Finder or Login Items, and the cached
# record still said "1.0.1" while 1.0.3 was the thing running.
#
# A fresh install is a brand new directory and never shows this, which is
# precisely why it survived so long — the bug is invisible to the machine
# that installs from scratch to test it, and visible only to everyone who
# upgrades. Touch the bundle so the mtime moves, then re-register so the
# refresh happens now rather than whenever macOS next rescans.
#
# Never fatal, for the reason the icon build is not: this is the update APPLY
# step, and a stale icon is not worth trading a working menu bar for.
touch "$APP_DIR"
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/\
LaunchServices.framework/Support/lsregister"
if [[ -x "$LSREGISTER" ]]; then
  "$LSREGISTER" -f "$APP_DIR" >/dev/null 2>&1 \
    || echo "WARNING: could not re-register the bundle — the icon and name" \
            "may lag until the next login." >&2
fi

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.ductran.ai-smartbar</string>
  <key>ProgramArguments</key>
  <array><string>$APP_DIR/Contents/MacOS/AISmartbar</string></array>
  <key>EnvironmentVariables</key>
  <dict>
    <!-- The bundle is a COPY in ~/Applications and cannot find the checkout
         on its own; device presence needs bin/ai-smartbar to announce this
         Mac to the other devices. -->
    <key>SMARTBAR_REPO_ROOT</key><string>$REPO</string>${CONFIG_PLIST}
  </dict>
  <key>RunAtLoad</key><true/>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/ai-smartbar.log</string>
</dict>
</plist>
EOF
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
echo "AI_smartbar $VERSION (native SwiftUI) installed — check the menu bar."
echo "Log: ~/Library/Logs/ai-smartbar.log"

# Self-updating is ON by default: a device nobody re-installs by hand should
# still pick up the next release. --no-auto-update opts this device out.
if [[ "$AUTO_UPDATE" == "1" ]]; then
  "$REPO/install/macos-update.sh" ${CHANNEL_ARG[@]+"${CHANNEL_ARG[@]}"} || \
    echo "WARNING: update agent NOT installed — this device will not self-update." >&2
fi
